* Configuration

this configuration file is inspired by [[http://pages.sachachua.com/.emacs.d/Sacha.html][Sacha Chua's Emacs configuration]].

** Personal information
#+BEGIN_SRC emacs-lisp :tangle yes
(setq user-full-name "David Becvarik"
      user-mail-address "ldj@l-d-j.org")
#+END_SRC

** Emacs initialization
*** Setup proper theme
#+BEGIN_SRC emacs-lisp :tangle yes
(load-theme 'misterioso)
#+END_SRC

*** Add package sources
#+BEGIN_SRC emacs-lisp :tangle yes
(package-initialize)
(unless (assoc-default "melpa" package-archives)
  (add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
;  (package-refresh-contents)
)
#+END_SRC

Use =M-x package-refresh-contents= to reload the list of packages
after adding these for the first time.

*** Setup use package

I use use-package for package management.

#+BEGIN_SRC emacs-lisp :tangle yes
(unless (package-installed-p 'use-package)
  (package-install 'use-package))
(require 'use-package)
(setq use-package-verbose t)
(setq use-package-always-ensure t)
(use-package auto-compile
  :config (auto-compile-on-load-mode))
(setq load-prefer-newer t)
#+END_SRC

*** Helm - interactive completion

#+BEGIN_SRC emacs-lisp :tangle yes
(use-package helm
  :diminish helm-mode
  :init
  (progn
    (require 'helm-config)
    (setq helm-candidate-number-limit 100)
    ;; From https://gist.github.com/antifuchs/9238468
    (setq helm-idle-delay 0.0 ; update fast sources immediately (doesn't).
          helm-input-idle-delay 0.01  ; this actually updates things
                                        ; reeeelatively quickly.
          helm-yas-display-key-on-candidate t
          helm-quick-update t
          helm-M-x-requires-pattern nil
          helm-ff-skip-boring-files t)
    (helm-mode))
  :bind (("C-c h" . helm-mini)
         ("C-h a" . helm-apropos)
         ("C-x C-b" . helm-buffers-list)
         ("C-x b" . helm-buffers-list)
         ("M-y" . helm-show-kill-ring)
         ("M-x" . helm-M-x)
         ("C-x c o" . helm-occur)
         ("C-x c s" . helm-swoop)
         ("C-x c y" . helm-yas-complete)
         ("C-x c Y" . helm-yas-create-snippet-on-region)
         ("C-x c b" . my/helm-do-grep-book-notes)
         ("C-x c SPC" . helm-all-mark-rings)))
(ido-mode -1) ;; Turn off ido mode in case I enabled it accidentally
#+END_SRC

*** Ace-jump
great cursor navigation

#+BEGIN_SRC emacs-lisp :tangle yes
(use-package ace-jump-mode
  :bind ("C-." . ace-jump-mode))
#+END_SRC

*** projectile
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package projectile
  :init (projectile-global-mode))

(use-package helm-projectile
  :ensure    helm-projectile
  :init
  (helm-projectile-on)
  :config
    (progn
      (setq projectile-completion-system 'helm)))
#+END_SRC

** org mode

*** Custom Todo Keywords
#+BEGIN_SRC emacs-lisp :tangle yes
(setq org-todo-keywords
  '((sequence "NEXT(n)" "TODO(t)" "WAIT(w)" "SOMEDAY(s)" "PROJECT(p)" "|" "DONE(d)" "CANCELED(c)")))
#+END_SRC
   
*** epresent
very interesting/clean way of doing presentation. Like zen mode :)

#+BEGIN_SRC emacs-lisp :tangle yes
(use-package epresent)
#+END_SRC

** Misc
*** Key suggestion
I use which key to guide me when my key chords struggles
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package which-key
  :init (which-key-mode)
  :config (setq which-key-popup-type 'side-window))
#+END_SRC
** Development
*** Python
For elpy I need following python modules
# Either of these
pip install rope
pip install jedi
# flake8 for code checks
pip install flake8
# importmagic for automatic imports
pip install importmagic
# and autopep8 for automatic PEP8 formatting
pip install autopep8
# and yapf for code formatting
pip install yapf

#+BEGIN_SRC emacs-lisp :tangle yes
(use-package elpy
  :init (elpy-enable))
#+END_SRC

*** Magit
I use magit for git manipulation. And I made magit to take fullscreen to do my git stuff. After ending it restores previous windows config.
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package magit
  :bind (("C-c g" . magit-status))
  :config
  ;; full screen magit-status
  (defadvice magit-status (around magit-fullscreen activate)
  (window-configuration-to-register :magit-fullscreen)
  ad-do-it
  (delete-other-windows))

  (defun magit-quit-session ()
  "Restores the previous window configuration and kills the magit buffer"
  (interactive)
  (kill-buffer)
  (jump-to-register :magit-fullscreen)))
#+END_SRC


